In [5]:
import numpy as np
import tensorflow as tf

In [16]:
with open("/content/Evo_IX.txt", 'r', encoding='utf-8') as file:
    evo_ix = file.read()

In [17]:
evo_ix

"The Mitsubishi Lancer Evolution IX, often referred to as the Evo 9, was the ninth iteration of Mitsubishi’s legendary performance car. The Lancer Evolution IX was produced between 2005 and 2007, and it stands as one of the most iconic cars in the performance sedan segment. Known for its motorsport pedigree and impressive engineering, the Evo IX became a favorite among car enthusiasts, particularly for its rallying heritage and track capabilities.\n\nMitsubishi’s Lancer Evolution series, which started in 1992, was developed with one goal in mind: to build a high-performance car that could excel in motorsports while offering street-going practicality. The Evo IX, like its predecessors, was designed as a performance sedan with a turbocharged engine, all-wheel drive, and exceptional handling characteristics.\n\nThe Evo IX was powered by a 2.0-liter turbocharged inline-four engine, known as the 4G63T, which had been refined over several iterations. This engine was capable of producing 276 

In [18]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()

In [19]:
tokenizer.fit_on_texts([evo_ix])

In [20]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"the": 108, "mitsubishi": 4, "lancer": 4, "evolution": 6, "ix": 29, "often": 2, "referred": 1, "to": 37, "as": 10, "evo": 31, "9": 1, "was": 37, "ninth": 1, "iteration": 1, "of": 44, "mitsubishi\\u2019s": 3, "legendary": 1, "performance": 29, "car": 24, "produced": 1, "between": 3, "2005": 1, "and": 50, "2007": 1, "it": 19, "stands": 1, "one": 7, "most": 4, "iconic": 1, "cars": 12, "in": 26, "sedan": 2, "segment": 1, "known": 2, "for": 12, "its": 29, "motorsport": 5, "pedigree": 2, "impressive": 4, "engineering": 5, "became": 2, "a": 36, "favorite": 1, "among": 2, "enthusiasts": 6, "particularly": 1, "rallying": 1, "heritage": 2, "track": 5, "capabilities": 3, "series": 3, "which": 11, "started": 1, "1992": 1, "developed": 1, "with": 17, "goal": 1, "mind": 3, "build": 2, "high": 7, "that": 10, "could": 5

In [21]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'to': 4,
 'was': 5,
 'a': 6,
 'evo': 7,
 'ix': 8,
 'performance': 9,
 'its': 10,
 'in': 11,
 'car': 12,
 'it': 13,
 'with': 14,
 'cars': 15,
 'for': 16,
 'which': 17,
 'as': 18,
 'that': 19,
 'on': 20,
 'handling': 21,
 'also': 22,
 'car’s': 23,
 'one': 24,
 'high': 25,
 'while': 26,
 'rear': 27,
 'evolution': 28,
 'enthusiasts': 29,
 'this': 30,
 'system': 31,
 'features': 32,
 'were': 33,
 'improve': 34,
 'helped': 35,
 'motorsport': 36,
 'engineering': 37,
 'track': 38,
 'could': 39,
 'designed': 40,
 'all': 41,
 'suspension': 42,
 'front': 43,
 'stability': 44,
 'featured': 45,
 'not': 46,
 'aggressive': 47,
 'mitsubishi': 48,
 'lancer': 49,
 'most': 50,
 'impressive': 51,
 'engine': 52,
 'by': 53,
 'had': 54,
 'power': 55,
 'advanced': 56,
 'ix’s': 57,
 'equipped': 58,
 'around': 59,
 'interior': 60,
 'driving': 61,
 'even': 62,
 'made': 63,
 'many': 64,
 'world': 65,
 'mitsubishi’s': 66,
 'between': 67,
 'capabilities': 68,
 'series': 69,
 'mind':

In [22]:
for sentence in evo_ix.split('\n'):
    print(sentence)
    token_sentence = tokenizer.texts_to_sequences([sentence])[0]
    print(token_sentence)


The Mitsubishi Lancer Evolution IX, often referred to as the Evo 9, was the ninth iteration of Mitsubishi’s legendary performance car. The Lancer Evolution IX was produced between 2005 and 2007, and it stands as one of the most iconic cars in the performance sedan segment. Known for its motorsport pedigree and impressive engineering, the Evo IX became a favorite among car enthusiasts, particularly for its rallying heritage and track capabilities.
[1, 48, 49, 28, 8, 97, 183, 4, 18, 1, 7, 184, 5, 1, 185, 186, 3, 66, 187, 9, 12, 1, 49, 28, 8, 5, 188, 67, 189, 2, 190, 2, 13, 191, 18, 24, 3, 1, 50, 192, 15, 11, 1, 9, 98, 193, 99, 16, 10, 36, 100, 2, 51, 37, 1, 7, 8, 101, 6, 194, 102, 12, 29, 195, 16, 10, 196, 103, 2, 38, 68]

[]
Mitsubishi’s Lancer Evolution series, which started in 1992, was developed with one goal in mind: to build a high-performance car that could excel in motorsports while offering street-going practicality. The Evo IX, like its predecessors, was designed as a performan

In [23]:
input_sequences = []

for sentence in evo_ix.split('\n'):

    token_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(token_sentence)):
        sequence = token_sentence[:i+1]
        input_sequences.append(sequence)


In [24]:
input_sequences[:5]

[[1, 48],
 [1, 48, 49],
 [1, 48, 49, 28],
 [1, 48, 49, 28, 8],
 [1, 48, 49, 28, 8, 97]]

In [25]:
max_length = max([len(x) for x in input_sequences])
max_length

90

In [26]:
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [27]:
input_sequences[:5]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1, 48],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  1, 48, 49],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0

In [28]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [29]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1], dtype=int32)

In [30]:
y[0]

48

In [31]:
num_classes = len(tokenizer.word_index) + 1
num_classes

460

In [32]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [33]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [48]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [49]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [51]:
history = model.fit(X, y, epochs=100)

Epoch 1/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.0523 - loss: 6.0309
Epoch 2/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0705 - loss: 5.3320
Epoch 3/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0884 - loss: 5.2367
Epoch 4/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0729 - loss: 5.2280
Epoch 5/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0952 - loss: 5.1259
Epoch 6/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1083 - loss: 4.9843
Epoch 7/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1492 - loss: 4.7903
Epoch 8/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1453 - loss: 4.6356
Epoch 9/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1834 - loss: 4.4826
Epoch 10/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2046 - loss: 4.3026
Epoch 11/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2381 - loss: 4.1286
Epoch 12/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy:

In [52]:
input_text = "Evolution IX was produced"

In [53]:
token_list = tokenizer.texts_to_sequences([input_text])[0]
token_list

[28, 8, 5, 188]

In [54]:
token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
token_list

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,  28,   8,   5, 188]],
      dtype=int32)

In [55]:
predicted = np.argmax(model.predict(token_list), axis=-1)
predicted

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([6])

In [56]:
for word, index in tokenizer.word_index.items():
    if index == predicted:
        print(word)

a


In [57]:
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
Evolution IX was produced a popular choice in the tuning
